version: '3.1'

services:
  pynoplia:
    build: .
    command: python3 -m wsgi --port=8575
    restart: always
    environment:
      - VIRTUAL_HOST=pyno.selfip.org
      - VIRTUAL_PORT=8575
    ports:
      - "8575:8575"
