version: '3.1'

services:
  pynoplia:
    build: .
    command: python3 -m wsgi
    restart: always
    environment:
      - VIRTUAL_HOST=pyno.alite.selfip.org
      - VIRTUAL_PORT=8585
    ports:
      - "8585:8585"
