version: '3.1'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  pynoplia:
    build: .
    command: python3 -m wsgi
    restart: always
    environment:
      - VIRTUAL_HOST=pyno.alite.selfip.org
      - VIRTUAL_PORT=8585
    ports:
      - "8585:8585"
